#include "Waterchip.h"

#include "Console/Runtime/KeyboardListener.h"
#include "Console/SDK/ConsoleSingleton.h"

describe("Toggle Console Open/Closed") begin

    setup begin
        // destroy console
    end

    it("initializes console on first toggle") begin
        expect(get_console_singleton) to_be_none;

        // call ConsoleRuntimeKeypressListener(true, get_console_shortcut_toggle);

        expect(get_console_singleton) not_to_be_none;
    end
end
