#include "Waterchip.h"
#include "Common/HexToDecimal.h"

describe("Hex to Decimal") begin

    it("can get decimal value for hexadecimal string") begin
        // Single digit numbers
        expect(HexToDecimal("0"))                to_equal(0);
        expect(HexToDecimal("9"))                to_equal(9);
        // Lowercase
        expect(HexToDecimal("a"))                to_equal(10);
        expect(HexToDecimal("f"))                to_equal(15);
        expect(HexToDecimal("aa"))               to_equal(170);
        expect(HexToDecimal("af"))               to_equal(175);
        expect(HexToDecimal("ea"))               to_equal(234);
        expect(HexToDecimal("ff"))               to_equal(255);
        expect(HexToDecimal("abcdef"))           to_equal(11259375);
        expect(HexToDecimal("abcdef0123456789")) to_equal(12379813738877118345);
        // Uppercase
        expect(HexToDecimal("A"))                to_equal(10);
        expect(HexToDecimal("F"))                to_equal(15);
        expect(HexToDecimal("AA"))               to_equal(170);
        expect(HexToDecimal("AF"))               to_equal(175);
        expect(HexToDecimal("EA"))               to_equal(234);
        expect(HexToDecimal("FF"))               to_equal(255);
        expect(HexToDecimal("ABCDEF"))           to_equal(11259375);
        expect(HexToDecimal("ABCDEF0123456789")) to_equal(12379813738877118345);
    end

    it("returns -1 if given a float") begin
        expect(HexToDecimal(123.456)) to_equal(-1);
        expect(HexToDecimal(420.69))  to_equal(-1);
    end

    it("returns integer value if given an int") begin
        expect(HexToDecimal(1))   to_equal(1);
        expect(HexToDecimal(69))  to_equal(69);
        expect(HexToDecimal(420)) to_equal(420);
    end

    it("returns -1 if given a string with invalid characters") begin
        expect(HexToDecimal("qwerty")) to_equal(-1);
        expect(HexToDecimal("g"))      to_equal(-1);
    end
end
